Repository Christiann12/Webprog-Repository, pull requests merged in 2021-02, with the labels that each got.

#16 Feat: Edited Welcome.php
  application/controllers/Main.php
  application/controllers/Welcome.php
  application/views/MainView.php
Labels: enhancement

#19 Added: Assets folder
  application/.htaccess
  application/assets/images/Chrysanthemum.jpg
  application/assets/images/Tulips.jpg
  application/assets/images/favicon.ico
Labels: enhancement

#27 feat: Added CSS and JS Framework
  application/assets/css/bootstrap.css
  application/assets/css/bootstrap.min.css
  application/assets/css/style.css
  application/assets/js/all.min.js
  application/assets/js/bootstrap.min.js
  application/assets/js/jquery-3.5.1.min.js
  application/assets/js/popper.min.js
  application/views/MainView.php
  application/views/headerNfooter/footer.php
  application/views/headerNfooter/header.php
Labels: enhancement

#29 feat: Added Header design
  application/assets/css/style.css
  application/assets/images/logo.jpg
  application/views/headerNfooter/header.php
Labels: enhancement

#39 feat: added footer design
  application/assets/css/style.css
  application/views/MainView.php
  application/views/headerNfooter/footer.php
  application/views/headerNfooter/header.php
Labels: enhancement

#43 feat: Created navbar functionality
  .htaccess
  application/assets/css/headerandfooterstyle.css
  application/config/config.php
  application/config/routes.php
  application/controllers/Main.php
  application/views/headerNfooter/footer.php
  application/views/headerNfooter/header.php
  application/views/pages/FAQ.php
  application/views/pages/MainView.php
Labels: enhancement

#44 Added: Ping.php
  application/views/pages/Ping.php
Labels: enhancement, good first issue

#45 Added SC: Ping and Financial Assistance Mockup
  mockup/Admin_dashboard.png
  mockup/Admin_ping.PNG
  mockup/Admin_support.PNG
  mockup/Admin_transaction.PNG
  mockup/Webpage_faqs.JPG
  mockup/Webpage_financialAssistance_1.png
  mockup/Webpage_financialAssistance_2.png
  mockup/Webpage_home.JPG
  mockup/Webpage_ping_1.png
  mockup/Webpage_ping_2.png
  mockup/Webpage_ping_3.png
  mockup/Webpage_support_1.png
  mockup/Webpage_support_2.png
  mockup/Webpage_support_3.png
  mockup/Webpage_support_4.png
  mockup/Webpage_tip_3.png
  mockup/Webpage_tips_1.png
  mockup/Webpage_tips_2.png
  mockup/Webpage_tips_4.png
  mockup/Webpage_transaction_1.png
  mockup/Webpage_transaction_2.png
  mockup/Webpage_transaction_3.png
  mockup/Webpage_transaction_4.png
Labels: documentation

#46 feat: Added About us section
  application/assets/css/headerandfooterstyle.css
  application/assets/css/homepageStyle.css
  application/assets/images/Desert.jpg
  application/views/headerNfooter/header.php
  application/views/pages/HomePage.php
Labels: enhancement

#50 feat: created last 3 sections for Homepage
  application/assets/css/headerandfooterstyle.css
  application/assets/css/homepage.css
  application/assets/css/homepageStyle.css
  application/assets/images/financialpreview.png
  application/assets/images/profile1.png
  application/assets/images/profile2.png
  application/assets/images/profile3.png
  application/assets/images/service1.png
  application/assets/images/service2.png
  application/views/headerNfooter/footer.php
  application/views/headerNfooter/header.php
  application/views/pages/HomePage.php
Labels: enhancement

#55 feat: Created controller for the admin page
  application/assets/css/simple-sidebar.css
  application/config/routes.php
  application/controllers/Admin.php
  application/views/adminpages/adminheaderfooter/adminfooter.php
  application/views/adminpages/adminheaderfooter/adminheader.php
  application/views/adminpages/pages/dashboard.php
  application/views/adminpages/pages/loginpage.php
  application/views/adminpages/pages/pingadmin.php
  application/views/adminpages/pages/supportadmin.php
  application/views/adminpages/pages/transactionadmin.php
  application/views/adminpages/pages/wrapper.php
Labels: enhancement

#62 feat: Created the design for sidebar and navbar for admin pages
  application/assets/css/simple-sidebar.css
  application/views/adminpages/adminheaderfooter/adminfooter.php
  application/views/adminpages/adminheaderfooter/adminheader.php
  application/views/adminpages/pages/dashboard.php
  application/views/adminpages/pages/pingadmin.php
  application/views/adminpages/pages/supportadmin.php
  application/views/adminpages/pages/transactionadmin.php
  application/views/adminpages/pages/wrapper.php
  application/views/headerNfooter/header.php
  application/views/pages/Tips_Accordion.html
  application/views/pages/myStyle.css
Labels: enhancement

#66 feat: Created login design
  application/assets/css/homepage.css
  application/assets/css/loginpage.css
  application/assets/css/simple-sidebar.css
  application/views/adminpages/adminheaderfooter/adminfooter.php
  application/views/adminpages/pages/loginpage.php
  application/views/adminpages/pages/wrapper.php
  application/views/pages/HomePage.php
Labels: enhancement

#74 feat: added onselected effect
  application/assets/css/headerandfooterstyle.css
  application/assets/css/simple-sidebar.css
  application/assets/js/adminheader.js
  application/assets/js/header.js
  application/views/adminpages/adminheaderfooter/adminfooter.php
  application/views/adminpages/pages/wrapper.php
  application/views/headerNfooter/footer.php
  application/views/headerNfooter/header.php
Labels: enhancement
